config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'gossips#index'
  get 'team', to: 'static_pages#team'
  get 'contact', to: 'static_pages#contact'
  resources :gossips do
    resources :comments, except: [:index, :show]
  end
  resources :cities, only: [:show]
  resources :users, only: [:show, :new, :create]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :gossip
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, presence: true, length: { in: 3..24 }
  validates :content, presence: true
  belongs_to :user
  has_many :markings
  has_many :tags, through: :markings
  has_many :comments
end

app/models/marking.rb
class Marking < ApplicationRecord
  belongs_to :tag
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :markings
  has_many :gossips, through: :markings
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  belongs_to :city
  has_many :gossips
  has_many :comments
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create]

  def new

  end

  def create
    @comment = Comment.new(content: params[:content], user_id: current_user.id, gossip_id: params[:gossip_id])
    if @comment.save
      redirect_to gossip_path(params[:gossip_id])
    else
      render 'new'
    end
  end

  def edit
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to @gossip
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:gossip_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @gossip
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :show]
  before_action only: [:edit, :update, :destroy] do |controller|
    controller.verify_author
  end

  def index
    @gossips = Gossip.all
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new

  end

  def create
  @gossip = Gossip.new(title: params[:title], content: params[:content], user_id: current_user.id)

    if @gossip.save
      flash[:success] = "Potin bien créé !"
      redirect_to gossips_path
    else
      render :new
    end
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(gossip_params)
      flash[:success] = "Potin édité !"
      redirect_to @gossip
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    flash[:success] = "Potin supprimé !"
    redirect_to gossips_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def welcome
    @gossips = Gossip.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # cherche s'il existe un utilisateur en base avec l’e-mail
    user = User.find_by(email: params[:email])

    # on vérifie si l'utilisateur existe bien ET si on arrive à l'authentifier (méthode bcrypt) avec le mot de passe 
    if user && user.authenticate(params[:password])
      log_in(user)
      flash.now[:success] = 'Bienvenue'
      redirect_to '/'

    else
      flash.now[:danger] = 'Connexion impossible, vérifiez votre mot de passe'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash.now[:success] = 'Vous êtes maintenant déconnecté'
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_gossips = @user.gossips
  end

  def new
    
  end

  def create
    @user = User.new(email: params[:email], password: params[:password], password_confirmation: params[:password_confirmation], first_name: params[:first_name], last_name: params[:last_name], age: params[:age], city_id: City.first.id)

    if @user.save
      log_in(@user)
      redirect_to gossips_path
    else
      render 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def verify_author
    unless Gossip.find(params[:id]).user_id == current_user.id
      flash[:danger] = "Action impossible : vous n'êtes pas l'auteur de ce potin !"
      redirect_to gossip_path
    end
  end

  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Veuillez vous connecter pour accéder à cette page"
      redirect_to new_session_path
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<h1>Page de la ville <%= @city.name %></h1>
<br/>

<h3>Voici les potins de <%= @city.name %></h3>
<br/>
<% @city.users.each do |user| %>
    <% user.gossips.each do |gossip| %>
        <div class="list-group">
            <a href="<%= gossip_path(gossip.id) %>" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><%= gossip.title %></h5>
                    <small>Créé le <%= gossip.created_at.to_time.strftime("%m/%d/%Y") %></small>
                </div>
              <p class="mb-1"><%= gossip.content %></p>
            </a>
        </div>
    <% end %>
<% end %>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Editer le commentaire</h1></br>

<p>
    <% if @comment != nil%>
        <% if @comment.errors.any? %>
        <p>Nous n'avons pas réussi à éditer le commentaire pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
            <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        <% end %>
    <% end %>
</p>

<%= form_for [@gossip, @comment] do |f| %>
  <div class="form-group">
    <label>Texte du commentaire</label>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">Modifier le commentaire</button>
    <a href="<%= gossip_comment_path(@gossip.id, @comment.id) %>" class="btn btn-warning" data-confirm="Êtes-vous certain de vouloir supprimer ce commentaire ?" data-method="delete">Supprimer</a>
  </div>
<% end %>

app/views/comments/new.html.erb
<h5>Ecrivez votre commentaire ici</h5>

<p>
    <% if @comment != nil%>
        <% if @comment.errors.any? %>
        <p>Nous n'avons pas réussi à créer le commentaire pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
            <% @comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        <% end %>
    <% end %>
</p>

<p>
    <%= form_tag gossip_comments_path, method: "post" do %>

      <%= label_tag 'Commentaire' %>
      <%= text_area_tag 'content'%>
      <br /> <br />

      <%= submit_tag "Valider" %>

    <% end %>
</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/gossips/edit.html.erb
<h1>Editer le potin</h1></br>

<p>
    <% if @gossip != nil%>
        <% if @gossip.errors.any? %>
        <p>Nous n'avons pas réussi à éditer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
            <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        <% end %>
    <% end %>
</p>

<%= form_for @gossip do |f| %>
  <div class="form-group">
    <label>Titre du potin</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Le potin</label>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">Modifier le potin</button>
  </div>

<% end %>

app/views/gossips/index.html.erb
<h1>Bienvenue à The Gossip Project !</h1><br/>

<% if current_user %>
<p><strong>Ravi de vous revoir, <%= current_user.first_name.capitalize %> !</strong></p>
<% end %>

<p>Retrouvez ici tous les potins de la communauté et partagez les votres avec les autres membres Gossip !</p>


<a href="<%=new_gossip_path%>" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Créer un potin</a><br/><br/>

<% @gossips.each do |gossip| %>
<div class="list-group">
  <a href="<%= gossip_path(gossip.id) %>" class="list-group-item list-group-item-action">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1"><%= gossip.title %></h5>
      <small>Créé le <%= gossip.created_at.to_time.strftime("%m/%d/%Y") %></small>
    </div>
    <p class="mb-1"><%= gossip.content %></p>
    <small><%= gossip.comments.count %> Commentaires</small>
  </a>
</div>
<% end %>

app/views/gossips/new.html.erb
<h5>C'est ici que vous pouvez partager votre potin, et tout le monde pourra en profiter !</h5>

<p>
    <% if @gossip != nil%>
        <% if @gossip.errors.any? %>
        <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
            <% @gossip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        <% end %>
    <% end %>
</p>

<p>
    <%= form_tag gossips_path, method: "post" do %>

      <%= label_tag 'Titre du potin' %>
      <%= text_field_tag 'title'%>
      <br /> <br />

      <%= label_tag 'Potin' %>
      <%= text_area_tag 'content'%>
      <br /> <br />

      <%= submit_tag "Valider" %>

    <% end %>
</p>

app/views/gossips/show.html.erb
<h1>Potin n°<%= @gossip.id %></h1>
<br/>
<p>
    <strong><%= @gossip.title %></strong><br/>
    <%= @gossip.content %><br/>
    <br/>
    Créé le <%= @gossip.created_at.to_time.strftime("%m/%d/%Y") %> par <a href="/users/<%= @gossip.user.id %>"> <%= @gossip.user.first_name %> <%= @gossip.user.last_name %></a> de <a href="<%= city_path(@gossip.user.city.id) %>"> <%= @gossip.user.city.name %> </a>
</p>

<p>
    <a href="<%= new_gossip_comment_path(@gossip.id) %>" class="btn btn-primary">Ecrire un commentaire</a>
</p>

<p>
    <% if @gossip.user_id == current_user.id %>
    <a href="<%= edit_gossip_path(@gossip.id) %>" class="btn btn-primary">Editer le potin</a>
    <% end %>
    <a href="<%= gossip_path(@gossip.id) %>" class="btn btn-warning" data-confirm="Êtes-vous certain de vouloir supprimer le potin ?" data-method="delete">Supprimer</a>
</p>

<p>
    <h4><%= @gossip.comments.count %> Commentaires</h4>
    <% @gossip.comments.each do |comment| %>
        <div class="list-group">
            <a href="<%= edit_gossip_comment_path(@gossip.id, comment.id) %>" class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><%= comment.user.first_name %></h5>
                <small><%= time_ago_in_words(comment.created_at) %></small>
            </div>
            <p class="mb-1"><%= comment.content %></p>
            </a>
        </div>
    <% end %>
</p>

app/views/users/new.html.erb
<h5>Remplissez le formulaire ci-dessous pour vous inscrire sur The Gossip Project !</h5>

<p>
    <% if @user != nil%>
        <% if @user.errors.any? %>
        <p>Nous n'avons pas réussi à créer votre compte pour la (ou les) raison(s) suivante(s) :</p>
        <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        <% end %>
    <% end %>
</p>

<p>
      <%= form_tag url_for(action: 'create'), method: "post" do %>

        <%= label_tag 'Prénom' %> 
        <%= text_field_tag 'first_name' %>
        <br /> <br />

        <%= label_tag 'Nom' %> 
        <%= text_field_tag 'last_name' %>
        <br /> <br />

         <%= label_tag 'Âge' %> 
        <%= text_field_tag 'age' %>
        <br /> <br />

         <%= label_tag 'Email' %> 
        <%= text_field_tag 'email' %>
        <br /> <br /> 

         <%= label_tag 'Mot de passe' %> 
        <%= text_field_tag 'password' %>
        <br /> <br />

         <%= label_tag 'Confirme ton mot de passe' %> 
        <%= text_field_tag 'password_confirmation' %>
        <br /> <br />

        <%= submit_tag "Je m'inscris" %> 

      <% end %>
</p>

app/views/users/show.html.erb
<h1>Profil de <%= @user.first_name %> <%= @user.last_name %></h1>
<br/>
<div class="card" style="width: 18rem;">
    <img class="card-img-top" src="http://www.aovc.org/wp-content/uploads/2015/10/photo-%C3%A0-venir-400x369.jpg" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %></h5>
        <p class="card-text"><a href="<%= city_path(@user.city.id) %>"> <%= @user.city.name %> </a> <br/> <%= @user.age %> ans</p>
        <p class="card-text"><%= @user.email %></p>
        <p class="card-text">"<%= @user.description %>"</p>
        <p class="card-text">Membre depuis le <%= @user.created_at.strftime("%m/%d/%Y") %></p>
    </div>
</div>
<br/>
<% @user_gossips.each do |gossip| %>
<p>
    Potin n°<%= gossip.id %> | <strong><a href="<%= gossip_path(gossip.id) %>"><%= gossip.title %></a></strong>
</p>
<% end %>